openapi: 3.0.3
info:
  title: BugExample.yml
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users':
    parameters:
      - name: filters
        in: query
        required: true
        schema:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            firstName:
              - Alice
            lastName:
              - Smith
              - Jones
        style: form
        explode: true
    get:
      summary: Get all users matching the filter
      responses:
        '200':
          description: Users Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                Get Users:
                  value:
                    - id: 142
                      firstName: Alice
                      lastName: Smith
                      email: alice.smith@gmail.com
                      dateOfBirth: '1997-10-31'
                      emailVerified: true
                      signUpDate: '2019-08-24'
                    - id: 123
                      firstName: Alice
                      lastName: Jones
                      email: alice.jones@gmail.com
                      dateOfBirth: '1997-10-30'
                      emailVerified: true
                      signUpDate: '2019-08-25'
      operationId: get-users-filtered
      description: Retrieve all users matching the filters.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      example:
        id: 142
        firstName: Alice
        lastName: Smith
        email: alice.smith@gmail.com
        dateOfBirth: '1997-10-31'
        emailVerified: true
        signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified